### ISSUE TITLE
Album art no longer visible in notification area

### ISSUE THREAD

**Issue by tristan957** [flathub/com.spotify.Client#129] opened 2020-04-30 03:51 UTC
I use GNOME and Fedora 32. Previously I had thought that Spotify had shown album art in the notification area, but recently I am noticing that is not the case.

Has something changed recently or is my memory faulty?

**Comment by TingPing** [comment] 2020-04-30 04:18
I believe its a regression in GNOME.

**Comment by tristan957** [comment] 2020-04-30 04:30
Ahh ok. Is there an upstream issue I can track? Otherwise I can reach out on IRC.

**Comment by Erick555** [comment] 2020-04-30 12:29
This never worked in KDE.

**Comment by JasonLG1979** [comment] 2020-05-26 18:17
> I believe its a regression in GNOME.

Nope, it's a Spotify bug. Basically in their MPRIS implementation from what I can gather the 1st part of the art url is hard coded to `https://open.spotify.com/open/` but they have moved their images to `https://i.scdn.co/image/` so the urls presented to the MPRIS controls are no longer valid.


https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/m-p/4920104

**Comment by tristan957** [comment] 2020-05-26 18:21
Hopefully someone notices. Thanks for the updates.

**Comment by JasonLG1979** [comment] 2020-05-26 18:30
> Hopefully someone notices. Thanks for the updates.

I wouldn't count on it. Linux support is minimal at best. That just adds to the many other ways that their MPRIS implementation is broken. You could always use my MPRIS GNOME Shell extension. [I workaround it.](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/commit/de48a04a1a4c3b96379dfe074f7dce667e33f09a)

**Comment by tristan957** [comment] 2020-05-26 18:51
:/ I will check out your extension. Thanks.

**Comment by TingPing** [comment] 2020-05-26 20:37
We really just need to make some dbus proxy that fixes all the broken MPRIS in Spotify.

**Comment by JasonLG1979** [comment] 2020-05-27 06:01
> We really just need to make some dbus proxy that fixes all the broken MPRIS in Spotify.

Once we did that the more or less static stuff can be just substituted and I may be able to get volume working on systems with pulse audio at least by just hooking into the pulse stream volume.

It would be nice though if it were a complete dbus app wrapper though. There are other issues that could fix the most user visible being multiple instances.

**Comment by Scotty-Trees** [comment] 2020-10-04 21:43
> > I believe its a regression in GNOME.
> 
> Nope, it's a Spotify bug. Basically in their MPRIS implementation from what I can gather the 1st part of the art url is hard coded to `https://open.spotify.com/image/` but they have moved their images to `https://i.scdn.co/image/` so the urls presented to the MPRIS controls are no longer valid.
> 
> https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/m-p/4920104

I'm on Pop!_OS Gnome 3.36.3 using the latest MPRIS extension from you ( https://extensions.gnome.org/extension/1379/mpris-indicator-button/ ), but unfortunately I don't see the Spotify cover artwork show. It simply shows the Spotify icon while playing a song. Is there anything I need to fix/change/edit in some config file to make it work? Otherwise other than that great extension btw!

**Comment by JasonLG1979** [comment] 2020-10-04 21:53
@Scotty-Trees

https://bugs.archlinux.org/task/62860#comment180555

**Comment by k-kirill** [comment] 2020-11-11 01:43
Just in case you don't mind messing up with binary transformation you can run this `bbe` command to work around the issue for the time being:
```
bbe -e 's|https://open.spotify.com/image|https://i.scdn.co/../././image|' spotify.bak > spotify
```
P.S. This funny `../././` addendum is to keep the length of the string intact.

**Comment by nikitagrygoriev** [comment] 2020-11-15 20:03
> Just in case you don't mind messing up with binary transformation you can run this `bbe` command to work around the issue for the time being:
> 
> ```
> cp spotify{,.bak}
> bbe -e 's|https://open.spotify.com/image|https://i.scdn.co/../././image|' spotify.bak > spotify
> ```
> 
> P.S. This funny `../././` addendum is to keep the length of the string intact.

Where would I do that? Somewhere inside ~/.local/share/flatpak/app/com.spotify.Client/?

**Comment by k-kirill** [comment] 2020-11-15 20:09
Yeah, fine the main `spotify` binary and "patch" it:
```
find . -name spotify -type f -size +10M
```

**Comment by nikitagrygoriev** [comment] 2020-11-15 20:45
> Yeah, find the main `spotify` binary and "patch" it:
> 
> ```
> find . -name spotify -type f -size +10M
> ```

Thank you for your reply!

Unfortunately, that did not work.
While Spotify is running, it returns:
`bash: spotify: Text file busy`
which makes sense(and proves that I am trying to edit the correct binary), but after closing Spotify and running the command, no changes occur. The same after reboot and/or using `sudo` for `bbe`.
I think it has changed from blank to this "note" icon, but the album cover is still not there.
![Screenshot from 2020-11-15 21-42-05](https://user-images.githubusercontent.com/33720703/99196293-bd039c80-278b-11eb-8a01-80c7c981fa14.png)

**Comment by k-kirill** [comment] 2020-11-15 20:53
Can you please run the following command after patching to see which URL is defined in the binary?
```
strings spotify | egrep '(https://open.spotify.com/image|https://i.scdn.co/../././image)'
```

**Comment by nikitagrygoriev** [comment] 2020-11-15 20:55
> Can you please run the following command after patching to see which URL is defined in the binary?
> 
> ```
> strings spotify | egrep '(https://open.spotify.com/image|https://i.scdn.co/../././image)'
> ```

https://i.scdn.co/../././image/%s

**Comment by k-kirill** [comment] 2020-11-15 21:03
That's weird as it works for me. Can you try these two URLs in your browser?
https://i.scdn.co/image/ab67616d00001e02d2212ede9ca1e4b0fb1b4b50
https://i.scdn.co/../././image/ab67616d00001e02d2212ede9ca1e4b0fb1b4b50

**Comment by nikitagrygoriev** [comment] 2020-11-15 21:08
> That's weird as it is what I've got and it works for me. Can you try these two URLs in your browser?
> https://i.scdn.co/image/ab67616d00001e02d2212ede9ca1e4b0fb1b4b50
> https://i.scdn.co/../././image/ab67616d00001e02d2212ede9ca1e4b0fb1b4b50

Both of them redirect to https://i.scdn.co/image/ab67616d00001e02d2212ede9ca1e4b0fb1b4b50

**Comment by k-kirill** [comment] 2020-11-15 21:39
Let's monitor D-Bus signals on changing songs in Spotify with the following command:
```
dbus-monitor |  grep -A1 mpris:artUr
```

**Comment by nikitagrygoriev** [comment] 2020-11-15 21:44
> Let's monitor D-Bus signals on changing songs in Spotify with the following command:
> 
> ```
> dbus-monitor | grep -A1 mpris:artUrl
> ```

![image](https://user-images.githubusercontent.com/33720703/99197652-15d73300-2794-11eb-838b-c66aa7d203ce.png)

**Comment by k-kirill** [comment] 2020-11-27 20:02
I was and I am at a loss to advise anything else. BTW, I use GNOME Shell 3.38.0, but I'm pretty sure your GNOME Shell is quite fresh as well. Maybe you use some system proxies, VPNs or some non-standard network managers. (I use NetworkManager, no VPN, no proxies).

**Comment by nikitagrygoriev** [comment] 2020-11-30 18:00
> I was and I am at a loss to advise anything else. BTW, I use GNOME Shell 3.38.0, but I'm pretty sure your GNOME Shell is quite fresh as well. Maybe you use some system proxies, VPNs or some non-standard network managers. (I use NetworkManager, no VPN, no proxies).

No worries! Huge thanks for trying. 
Yeah, I am on GNOME 3.38.1, no VPNs, no proxies. Maybe one day they will fix it lol

**Comment by carlocastoldi** [comment] 2021-04-28 10:47
Yeah. Same problem here on KDE.
I see the right url with `dbus-monitor` and yet the media applet doesn't show any thumbnail for spotify :\

**Comment by JasonLG1979** [comment] 2021-04-28 19:55
> Yeah. Same problem here on KDE.
> I see the right url with `dbus-monitor` and yet the media applet doesn't show any thumbnail for spotify :\

To recap:

https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/m-p/4929877

This affects all versions of Spotify and is not flatpak specific. Basically Spotify provides a bogus url doing a string replace of `open.spotify.com` with `i.scdn.co` should get you a valid url.

For GNOME users it's a double whammy. On many distros GNOME is configured in such a way that Gio used in GNOME Shell (and any Shell extensions) can not access remote files. So since MPRIS art url is a remote file it can't be displayed even if a string replace is done on the url.

The right way to fix this is for Spotify to download the cover and cache it locally and then use that cached cover art for MPRIS.

I would not count on them fixing this anytime soon though considering this is already a year old issue and it's not even the oldest unfixed bug.

**Comment by carlocastoldi** [comment] 2021-04-28 23:44
I actually knew about GNOME's problem, but that's why i reported about the bug on KDE. I tried to fix the binary with the previously-posted fix and yet it didn't work.

I don't think KDE applies GNOME's rule on remote files because  it shows YouTube thumbnails with no problems

**Comment by JasonLG1979** [comment] 2021-04-29 05:11
> I actually knew about GNOME's problem, but that's why i reported about the bug on KDE. I tried to fix the binary with the previously-posted fix and yet it didn't work.

It didn't work for @nikitagrygoriev for whatever reason either? This an old well know bug that's not flatpak specific, it's upstream and the only thing we could do is write a MPRIS wrapper which I'm not even really sure if it's worth it. Better time would be spent on projects like librespot to someday enable a fully functional Spotify app for Linux. The Spotify desktop app as it sits is pretty bad, you can only put so much lipstick on a pig.

A better quick fix for you would be to patch KDE's media applet to do the string replace.

I'm not trying to be mean, but at this point, for this issue, another "Me too" is just noise.

**Comment by carlocastoldi** [comment] 2021-04-29 09:19
Yeah I am sorry for having necro'd this issue. You are right that working on this would be a pretty much waste of time.
Thanks for taking the time answering tho. I appreciate it!

**Comment by elegos** [comment] 2021-08-28 00:50
Hello!

Since the Spotify team doesn't love Linux that much, I've created a [Spotify mpris:artUrl binary patcher, written in Python](https://gist.github.com/elegos/2eb0a569d1fc5411b4661e38f89ab3fd).

Just copy/paste it in a file, `chmod +x` it and launch via `sudo ./spotify-mpris-art-fix.py --patch`.

My installation is in `/usr/share/spotify-client/spotify`, but you can specify yours, if differs, via the `--bin-file` option.

For all the options, read the source, or just run the script with `-h` :smiley:

**Comment by msrn** [comment] 2021-09-22 08:04
There are [reports ](https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/m-p/5258415/highlight/true#M20697)that v1.6.7 fixes the wrong url. Can others confirm this?

**Comment by juxuanu** [comment] 2021-09-22 08:06
Not here... And I can't seem to find the binary in Flatpak to patch it.

**Comment by msrn** [comment] 2021-10-01 10:09
For me the latest Flatpak which uses the [latest snap](https://github.com/flathub/com.spotify.Client/commit/8de3145dd2df7ece39f520457d4efdc8608bda9a), shows album art in notification area. With Ubuntu 21-04

**Comment by msrn** [comment] 2022-05-29 22:32
Shouldn't this be closed?

**Closed** 2022-07-19 20:53 UTC
Labels: upstream
