### ISSUE TITLE
Unable to install (Connection Terminated Unexpectedly)

### ISSUE THREAD

**Issue by Garamari** [flathub/com.spotify.Client#108] opened 2019-12-17 22:46 UTC
Flatpak will fail to install Spotify when downloading the .deb file as the connection will cut off suddenly, it's also impossible to download the .deb file through a browser as that will also fail. I tried installing other Flatpaks to be sure it wasn't my own connection but it seems this is the only one I found having the problem.

**Comment by TingPing** [comment] 2019-12-18 09:30
> it's also impossible to download the .deb file through a browser as that will also fail

Well then its completely their servers fault and nothing we can do about it.

**Comment by Garamari** [comment] 2019-12-18 16:52
Sorry I was under the impression you could have it download from a more reliable source. Is there a way I can get it to use the .deb file locally instead of downloading one?

**Comment by 7oxicshadow** [comment] 2019-12-18 19:47
I can confirm the same problem occurs for me on Fedora 31 (KDE). It appears that the server rejects the connection after downloading approx 50% of the file. 

If you download via a browser the same thing happens BUT if you use a browser such as Firefox that allows "retry" within the download monitor you can successfully get the file after 2 or 3 attempts.

Is there anywhere we can put the file so that the install script will use it? If not is it possible to modify the script to have X number of retry attempts (assuming libsoup supports resuming) to download the file in chunks.

**Comment by TingPing** [comment] 2019-12-19 01:52
> Sorry I was under the impression you could have it download from a more reliable source.

Spotify is the only source...

> Is there a way I can get it to use the .deb file locally instead of downloading one?

No.

**Comment by fariasmarcos** [comment] 2019-12-19 14:49
I'm also on Fedora 31, and I can confirm the issue. Unfortunately it seems like a spotify's server side problem.

**Comment by ther0n** [comment] 2019-12-19 18:43
> Sorry I was under the impression you could have it download from a more reliable source. Is there a way I can get it to use the .deb file locally instead of downloading one?


For now you can manually build the flatpak:
1. Upload `spotify.deb` somewhere I used https://tmp.ninja based on a quick DuckDuckGo search for temporary file hosting
2. `git clone --recursive https://github.com/flathub/com.spotify.Client.git`
3. `cd com.spotify.Client`
4. edit line 174 of `com.spotify.Client.json` to match the url where you uploaded `spotify.deb`
5. Build and install: `flatpak-builder -v --force-clean --sandbox --delete-build-dirs --user --install --arch x86_64 --bundle-sources build com.spotify.Client.json`

I'm not sure if you will receive updates if you install this way so it's only temporary.

**Comment by gayanper** [comment] 2019-12-19 18:53
Firefox trick works

**Comment by ArjenR** [comment] 2019-12-20 12:18
The connections is dropped after a certain amount of bytes. Probably some sort of ddos handling going on. wget for example will retry a few times and will get the complete file eventually, always continuing from where the connection was dropped.

It looks like flatpak does not keep the partial file and restarts the download instead of resuming. So yes, the issue is on the server end but the partial download is not kept for extra-data files where I think it is for others downloads during a session.

Using --verbose shows libsoup is used and I doubt if that library supports resuming a partial download.

**Comment by rifkiaz** [comment] 2019-12-20 18:57
same problem with openSUSE Tumbleweed with GNOME

**Comment by modzilla99** [comment] 2019-12-20 19:58
> > Sorry I was under the impression you could have it download from a more reliable source. Is there a way I can get it to use the .deb file locally instead of downloading one?
> 
> For now you can manually build the flatpak:
> 
>     1. Upload `spotify.deb` somewhere I used https://tmp.ninja based on a quick DuckDuckGo search for temporary file hosting
> 
>     2. `git clone --recursive https://github.com/flathub/com.spotify.Client.git`
> 
>     3. `cd com.spotify.Client`
> 
>     4. edit line 174 of `com.spotify.Client.json` to match the url where you uploaded `spotify.deb`
> 
>     5. Build and install: `flatpak-builder -v --force-clean --sandbox --delete-build-dirs --user --install --arch x86_64 --bundle-sources build com.spotify.Client.json`
> 
> 
> I'm not sure if you will receive updates if you install this way so it's only temporary.

Works great! But for ease of use you could serve the deb with python by running python3 -m http.server 8080 and  then use the URL http://127.0.0.1:8080/sth.deb

**Comment by damluk** [comment] 2019-12-21 10:52
Why do you use repository-origin here [1], instead of the documented [2] repository.spotify.com

[1] https://github.com/flathub/com.spotify.Client/blob/1ea58c254287bc94416d55d1b09b673401d5b8a8/com.spotify.Client.json#L167
[2] https://www.spotify.com/us/download/linux/

**Comment by ArjenR** [comment] 2019-12-21 13:22
>  instead of the documented [2] repository.spotify.com

Does that url actually work properly for you? I receive the wrong certificate when I access that site, a  wildcard for *.cloudfront.org

**Comment by damluk** [comment] 2019-12-21 13:37
The documented scheme is http not https.

**Comment by Erick555** [comment] 2019-12-21 15:35
> Why do you use repository-origin here [1], instead of the documented [2] repository.spotify.com

> The documented scheme is http not https.

So, you have the answer.

**Comment by damluk** [comment] 2019-12-21 15:43
No I don't. The whole Debian/Ubuntu ecosystem uses http for its mirrors. Spotify could disable public access to repository-origin completely. Would you remove the package from flathub then?

**Comment by geext-dk** [comment] 2019-12-21 18:42
It downloads successfully when changing `https` to `http` and `repository-origin` to `repository`

**Comment by TheEquity** [comment] 2019-12-22 08:43
Having the same issue with Arch Linux KDE, not sure if desktop enviornment matters though. I'd expect this problem to be fixed by now, but apparently it hasn't....

**Comment by Erick555** [comment] 2019-12-22 10:54
> No I don't. The whole Debian/Ubuntu ecosystem uses http for its mirrors.

Yes, and this is the result: https://blog.packagecloud.io/eng/2018/02/21/attacks-against-secure-apt-repositories . You asked why and answered it yourself even if you don't like it

> Spotify could disable public access to repository-origin completely

The could even drop linux support completely.

> Would you remove the package from flathub then?

Not my decision to take.

**Comment by damluk** [comment] 2019-12-22 11:03
> > The whole Debian/Ubuntu ecosystem uses http for its mirrors.
> 
> Yes, and this is the result: https://blog.packagecloud.io/eng/2018/02/21/attacks-against-secure-apt-repositories.

While the redirect bug earlier this year was pretty bad, all points of your blogpost are irrelevant for flathub, as the download is verified against a hardcoded sha256sum in the json file.

**Comment by Erick555** [comment] 2019-12-22 11:07
Not my blogpost. The whole Debian/Ubuntu ecosystem is irrelevant for flathub but it was you who mentioned it. You can guess from where this hardcoded sha256sum comes from.

**Comment by damluk** [comment] 2019-12-22 11:41
> The whole Debian/Ubuntu ecosystem is irrelevant for flathub but it was you who mentioned it.

It is not. My point is that Spotify follows the usual Debian practice, and they would still do, if they shut down repository-origin. Flathub is not in their scope, so why would they "fix" repository-origin's partial-download issue, when it isn't even an issue from their perspective? Maybe they did it on purpose.

> You can guess from where this hardcoded sha256sum comes from.

What is your point? That you do not trust a new sha256sum if it is not obtained via https? The blogpost does not say that the cryptography is broken, but the package manager was. If flathub maintainers do not trust apt, they can still verify GPG signatures manually.
Also, as long as repository-origin exists and .deb files are downloadable from it at all, the maintainers can sha256sum https-obtained .deb files themselves and refer to the http repository.

**Comment by damluk** [comment] 2019-12-22 11:48
One point I must admit though, is that the issue might come up with the http-repository as well, because apt can handle partial downloads fine, so it is a non-issue for Spotify even when repository-origin is intended for public use.

**Comment by Erick555** [comment] 2019-12-22 12:07
> That you do not trust a new sha256sum if it is not obtained via https?

Do you?

> The blogpost does not say that the cryptography is broken, but the package manager was. If flathub maintainers do not trust apt, they can still verify GPG signatures manually.

The blogpost shows that lack of additional transport security opens attack vectors impossible to execute otherwise. I don't know how trusting apt is relevant in flatpak context where apt isn't involved at all. Flatpak verify extra-data only by hash & file size. Unfortunately spotify doesn't sign deb directly thus manual verifying signatures there is annoying. They also roll-out new keys without notice.

**Comment by Erick555** [comment] 2019-12-22 12:09
Either way here's the hotfix: https://github.com/flathub/com.spotify.Client/pull/109

**Closed** 2019-12-22 12:18 UTC

**Comment by damluk** [comment] 2019-12-22 12:26
> Either way here's the hotfix: #109

Thank you.

**Comment by memeplex** [comment] 2020-11-10 18:53
I'm still getting:

![image](https://user-images.githubusercontent.com/2845433/98718217-e75cf080-236c-11eb-831d-4a8298b50c3a.png)

**Comment by damluk** [comment] 2020-11-10 19:44
Can you reproduce it with curl / wget?

**Comment by memeplex** [comment] 2020-11-10 19:46
![image](https://user-images.githubusercontent.com/2845433/98725728-48d48d80-2374-11eb-9093-aed98f079781.png)

**Comment by damluk** [comment] 2020-11-10 20:17
Very interesting. I can reproduce this with the resolved addresses in your screenshot. My cloudfront region, however, is intact.
Try a download while using one of the IPs below.
```
repository.spotify.com is an alias for d2czmavkeme1ql.cloudfront.net.
d2czmavkeme1ql.cloudfront.net has address 54.230.53.147
d2czmavkeme1ql.cloudfront.net has address 54.230.53.171
d2czmavkeme1ql.cloudfront.net has address 54.230.53.84
d2czmavkeme1ql.cloudfront.net has address 54.230.53.109
```

**Comment by memeplex** [comment] 2020-11-10 21:20
Should this be reopen? It seems to me that the underlying problem is that the downloading mechanism in Flatpak is not robust enough, as last year the problem is solved with a few retrials.

**Comment by memeplex** [comment] 2020-11-10 21:25
> Try a download while using one of the IPs below.

```
[carlos@localhost com.spotify.Client]$ flatpak-builder -v --force-clean --sandbox --delete-build-dirs --user --install --arch x86_64 --bundle-sources build com.spotify.Client.json
FB: Running: git config --get user.email
FB: Running: git config --get user.name
FB: Running: flatpak info --arch=x86_64 --show-commit org.freedesktop.Sdk 20.08
error: org.freedesktop.Sdk/x86_64/20.08 not installed
Failed to init: Unable to find sdk org.freedesktop.Sdk version 20.08
```

It's my first time building a flatpak, is there any way to automatically download the required runtime?

**Comment by steelcowboy** [comment] 2020-11-10 21:31
I was able to repro as well. I put the following line into /etc/hosts:
```
repository.spotify.com 54.230.53.147
```
And it worked perfectly. I'm located on the US West Coast, so it seems to be an issue in this region.

**Comment by damluk** [comment] 2020-11-10 21:37
> Should this be reopen? It seems to me that the underlying problem is that the downloading mechanism in Flatpak is not robust enough, as last year the problem is solved with a few retrials.

The downloading mechanism is probably implemented in flatpak itself not in every single package as this one.

**Comment by memeplex** [comment] 2020-11-10 21:44
> The downloading mechanism is probably implemented in flatpak

I've created https://github.com/flatpak/flatpak/issues/3952 for the more general issue.

**Comment by memeplex** [comment] 2020-11-11 20:56
This doesn't seem to be temporary, one day later it's still the same.

**Comment by ZakB-K** [comment] 2020-11-15 08:12
I am also currently having this issue on Fedora 33. Happy to test possible solutions if anyone has an idea.

**Comment by damluk** [comment] 2020-11-15 09:02
> I am also currently having this issue on Fedora 33. Happy to test possible solutions if anyone has an idea.

Either try @steelcowboy's `/etc/hosts` idea or this one:

```
demo@vm:~ ls -l ~/.local/share/flatpak
insgesamt 16
drwxr-xr-x 3 demo demo 4096 Nov 10 23:12 app
drwxr-xr-x 2 demo demo 4096 Nov  8  2018 db
drwxr-xr-x 4 demo demo 4096 Nov 10 23:12 exports
drwxr-xr-x 7 demo demo 4096 Nov 10 23:27 repo
demo@vm:~ wget -q http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.42.622.gbd112320-37_amd64.deb
demo@vm:~ sha256sum spotify-client_1.1.42.622.gbd112320-37_amd64.deb 
101a3699197659b8bc60a4fd8b579e63cc494e7abd089c45306559329af4a868  spotify-client_1.1.42.622.gbd112320-37_amd64.deb
demo@vm:~ mkdir -p ~/.local/share/flatpak/extra-data/101a3699197659b8bc60a4fd8b579e63cc494e7abd089c45306559329af4a868
demo@vm:~ mv spotify-client_1.1.42.622.gbd112320-37_amd64.deb ~/.local/share/flatpak/extra-data/101a3699197659b8bc60a4fd8b579e63cc494e7abd089c45306559329af4a868/spotify.deb
demo@vm:~ ls -l ~/.local/share/flatpak/extra-data/101a3699197659b8bc60a4fd8b579e63cc494e7abd089c45306559329af4a868/spotify.deb 
-rw-rw-r-- 1 demo demo 126293582 Sep 16 16:54 /home/demo/.local/share/flatpak/extra-data/101a3699197659b8bc60a4fd8b579e63cc494e7abd089c45306559329af4a868/spotify.deb
demo@vm:~ flatpak install -vv com.spotify.Client
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/demo/.local/share/flatpak
Looking for matches…
F: Fetching summary file for remote ‘flathub’
Found similar ref(s) for ‘com.spotify.Client’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: 
F: Fetching summary file for remote ‘flathub’
F: Transaction: install flathub:app/com.spotify.Client/x86_64/stable[*]
F: Looking for remote metadata updates for flathub
F: marking op install:app/com.spotify.Client/x86_64/stable resolved to fc826a0d6e7c7390f8dcc571e120792b9bc101071e3948034a674ea214f2683c
F: Updating dependent runtime runtime/org.freedesktop.Platform/x86_64/20.08
F: Transaction: update flathub:runtime/org.freedesktop.Platform/x86_64/20.08[$old]
F: marking op update:runtime/org.freedesktop.Platform/x86_64/20.08 resolved to 99666aa95651104a247e446309140c3641d0f43902240b57de11657a2fc1944f
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/20.08[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.nvidia-450-80-02/x86_64/1.4[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/20.08[/de]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.openh264/x86_64/2.0[*]
F: marking op install/update:runtime/org.freedesktop.Platform.openh264/x86_64/2.0 resolved to 73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b
F: marking op install/update:runtime/org.freedesktop.Platform.Locale/x86_64/20.08 resolved to e59956b0c9e66dbba44122d8130c3ef009d66b6259e20a29c4f6aa4347316238
F: marking op install/update:runtime/org.freedesktop.Platform.GL.nvidia-450-80-02/x86_64/1.4 resolved to e2be321e5268f6b617ca836431f2e281cb57d6e3f7ea2e8ee7559e39b2dbd644
F: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 resolved to 82a8e234463fcb58ccd655b09dafbfe751ea785816c0927053f2a6a9a8fad73d

com.spotify.Client permissions:
    ipc	network	pulseaudio	x11	dri	file access [1]	dbus access [2]	bus ownership [3]	tags [4]

    [1] xdg-music:ro, xdg-pictures:ro
    [2] org.freedesktop.Notifications, org.gnome.SessionManager, org.gnome.SettingsDaemon
    [3] org.mpris.MediaPlayer2.spotify
    [4] proprietary


 1.	   	com.spotify.Client	stable	i	flathub	< 138,2 MB

Proceed with these changes to the system installation? [Y/n]: 
Installing…                                                                                       F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
F: flatpak_dir_pull: Using commit fc826a0d6e7c7390f8dcc571e120792b9bc101071e3948034a674ea214f2683c for pull of ref app/com.spotify.Client/x86_64/stable from remote flathub

Installing…                        0%  0 Bytes/s
Installing… █▊                     9%
Installing… ██▏                   11%
Installing… ██▌                   13%  7,7 MB/s
Installing… ██▌                   13%  3,8 MB/sF: Loading extra-data from local file /home/demo/.local/share/flatpak/extra-data/101a3699197659b8bc60a4fd8b579e63cc494e7abd089c45306559329af4a868/spotify.deb
F: Calling system helper: Deploy
F: Calling system helper: RunTriggers
Installation complete.
```

The URL for wget, the expected sha256sum and the file name `spotify.deb` can be cross-checked with `extra-data` from `https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json`
