### ISSUE TITLE
Clicking on the notification doesn't raise Spotify

### ISSUE THREAD

**Issue by memeplex** [flathub/com.spotify.Client#136] opened 2020-09-16 22:47 UTC
I'm on up-to-date Fedora 32 (Gnome 3.36.6). I've installed Spotify flatpak 1.1.26.501. When I click on the Spotify "notification" next/prev/play/stop controls work as expected, but clicking on the song title doesn't raise and focus the Spotify window as I believe was the usual behavior with every other Spotify installation I used.

**Comment by TingPing** [comment] 2020-09-16 23:57
I don't think this can be sanely fixed by this package since we don't control any of the notification behavior.

**Comment by memeplex** [comment] 2020-09-17 00:12
I don't know how this usually works, ithe "notification" is kind of an applet, maybe it sends a signal to the window or a dbus message, can flatpak interfere with that? Strangely enough other messages seems to be working (for example, the play/pause functionality works ok).

**Comment by memeplex** [comment] 2020-09-17 00:41
I has been playing a bit with MPRIS, there is a Raise method and a CanRaise property, the first one does nothing and the second one has false as its value:

```
~:: dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2' string:'CanRaise'
method return time=1600303200.716590 sender=:1.83 -> destination=:1.112 serial=79 reply_serial=2
   variant       boolean false
```

Will try the same against the non-flatpak version.

**Comment by TingPing** [comment] 2020-09-17 01:00
Oh yes MPRIS raising being broken is just a Spotify bug and a duplicate of #4

**Closed by TingPing** 2020-09-17 01:00 UTC

**Comment by memeplex** [comment] 2020-09-17 01:04
I don't think so, because Shell seems to be doing something else (mpris.js):

```
        if (this._mprisProxy.DesktopEntry) {
            let desktopId = '%s.desktop'.format(this._mprisProxy.DesktopEntry);
            app = Shell.AppSystem.get_default().lookup_app(desktopId);
        }
```

And the DesktopEntry property is `spotify`:

```
~:: dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2' string:'DesktopEntry'
method return time=1600304132.873396 sender=:1.92 -> destination=:1.93 serial=45 reply_serial=2
   variant       string "spotify"
```

**Comment by memeplex** [comment] 2020-09-17 01:40
Is it possible to provide a spotify.desktop file within the flatpak? Maybe a symlink? DesktopEntry is specified to be

> The basename of an installed .desktop file which complies with the Desktop entry specification, with the ".desktop" extension stripped.

I know the best solution would be for upstream to package the flatpak with the right DesktopEntry value, but I don't see that happening any time soon. From a practical point of view, can adding a spotify.desktop file cause any problem? Or maybe is it simply forbidden?

**Comment by TingPing** [comment] 2020-09-17 23:39
> Is it possible to provide a spotify.desktop file within the flatpak? Maybe a symlink? DesktopEntry is specified to be

No.
