### ISSUE TITLE
TLS handshake with server doesn't work anymore

### ISSUE THREAD

**Issue by rfc2822** [flathub/com.spotify.Client#117] opened 2020-01-28 12:38 UTC
Hello,

Since a few days, the current version from Flatpak can't connect to the streaming servers anymore (no images, no sounds except for cached songs; Manjaro Linux 18.1.5). The client sends TLS Alert: Unknown certificate after receiving the cert from the server.

Deleting the cache dir didn't help. Installing the official snap (1.1.10.546-ge08ef575) helped, so maybe the package is outdated?

**Comment by Erick555** [comment] 2020-01-28 13:09
This is [known issue](https://github.com/flathub/com.valvesoftware.Steam/issues/526#issuecomment-578234761) that happens on Arch Linux and derivatives like Manjaro. it affect many flatpaks and need to be fixed in runtime. The fix is [prepared here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2255).

**Comment by Erick555** [comment] 2020-01-28 13:10
This is also duplicate of https://github.com/flathub/com.spotify.Client/issues/116

**Closed** 2020-01-28 14:29 UTC

**Comment by rfc2822** [comment] 2020-01-28 17:14
Ah, thanks for the information and your efforts!
