### ISSUE TITLE
Can't add local files and settings menú does not work

### ISSUE THREAD

**Issue by jmarinho73** [flathub/com.spotify.Client#24] opened 2018-01-20 10:51 UTC
Hi
I have Flatpak's Spotify app installed on my system (Fedora 27 Workstation Gnome) and I have some issues that I don't have with Ubuntu 14.04 or 16.04 and the .deb version. For example I can't add and play local files (file format doesn't matter, whatever file) and I can't open and or interact with the app menu.
![captura de pantalla de 2018-01-20 11-39-35 png](https://user-images.githubusercontent.com/21139123/35182564-ddb061b0-fdd7-11e7-8b8b-1950ee5d58fb.png)

**Comment by TingPing** [comment] 2018-01-20 11:03
> interact with the app menu.

Can't reproduce that. Are you on Wayland? If so try Xorg perhaps.

>  I can't add and play local files

I can reproduce adding folders is broken but files in your music folder *should* work.

**Comment by TingPing** [comment] 2018-01-20 11:26
This should fix at least one bug in the folder selector: https://github.com/flatpak/freedesktop-sdk-images/pull/75 (will be merged monday probably)

**Comment by Lonsfor** [comment] 2018-01-20 12:49
it seems that not being able to click on the settings menu is not a flatpak exclusive problem and maybe not a Wayland/Xorg problem https://community.spotify.com/t5/Desktop-Linux/Settings-don-t-open-on-Linux/td-p/1478736

**Comment by jmarinho73** [comment] 2018-01-20 17:50
I just trying on a virtual machine with ubuntu 14.04 installed and the .deb version of Spotify up to date. I don't have there none of this issues. On the flatpak version when I try to add local files, firstly, I only can navigate to my music folder and only can select the music folder or a folder inside it but that not work. I attach two screenshots.
![seleccion_001](https://user-images.githubusercontent.com/21139123/35186221-f7cbed88-fe10-11e7-98f7-352e0b6c4532.png)
![seleccion_002](https://user-images.githubusercontent.com/21139123/35186222-f7eac83e-fe10-11e7-9474-9f14c859562e.png)
It's indifferent if I am on a Wayland or Xorg session.
If I launch Spotify from the console I get this messages:
```
flatpak run com.spotify.Client
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)

(process:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0120/184257.469204:ERROR:proxy_config_service_linux.cc(274)] Error requesting gconf directory: Failed to activate configuration server: org.freedesktop.DBus.Error.ServiceUnknown


(process:71): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

(zenity:71): Gtk-WARNING **: GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER is not supported by GtkFileChooserNativePortal
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:71): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(zenity:71): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(zenity:71): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(zenity:71): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```
The last one message repeated a lot of times. Hope this helps.

**Comment by TingPing** [comment] 2018-01-20 18:00
As I linked the folder problem will be fixed.

The menu problem is nothing we can solve and as mentioned it works for some.

**Comment by Lonsfor** [comment] 2018-01-30 02:38
I am sorry to annoy you @TingPing but did something happened that the fix for the folder selector bug wasn't merged yet?

**Comment by TingPing** [comment] 2018-01-30 15:48
@Lonsfor Alex was at a conference for a week he just got back, it will be merged soon.

**Comment by Lonsfor** [comment] 2018-01-30 21:07
Ok thanks

**Comment by Lonsfor** [comment] 2018-03-20 20:17
its been almost two months and local files still aren't working

**Comment by TingPing** [comment] 2018-03-21 10:38
The bug fix was merged, just waiting on an update.

**Comment by jmarinho73** [comment] 2018-03-28 15:16
Today I get and update of flatpak and some things changed, but I can't play local files yet. Now I can add local files to the app but the app does not play it like you can see in the screenshoot:
![image](https://user-images.githubusercontent.com/21139123/38038353-1013e78c-32ab-11e8-8583-fb93f62ef495.png)
When I try to play a local file, I get the error that you can see on the screenshoot. The files are on my computer and I play them normally with Rhythmbox. 
More information:
Output of flatpak list:

Referencia                                            Opcións      
com.spotify.Client/x86_64/stable                      system,current
org.telegram.desktop/x86_64/stable                    system,current
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0 system,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6       system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6            system,runtime
org.freedesktop.Platform/x86_64/1.6                   system,runtime
org.kde.Platform/x86_64/5.9                           system,runtime

Output of flatpak info:
Last metadata expiration check: 6 days, 18:17:59 ago on Mér 21 Mar 2018 21:49:34 CET.
Installed Packages
Name         : flatpak
Version      : 0.10.4
Release      : 1.fc27
Arch         : x86_64
Size         : 4.4 M
Source       : flatpak-0.10.4-1.fc27.src.rpm
Repo         : @System
From repo    : updates
Summary      : Application deployment framework for desktop apps
URL          : http://flatpak.org/
License      : LGPLv2+
Description  : flatpak is a system for building, distributing and running
             : sandboxed desktop applications on Linux. See
             : https://wiki.gnome.org/Projects/SandboxedApps for more
             : information.

Available Packages
Name         : flatpak
Version      : 0.10.3
Release      : 1.fc27
Arch         : i686
Size         : 1.0 M
Source       : flatpak-0.10.3-1.fc27.src.rpm
Repo         : updates
Summary      : Application deployment framework for desktop apps
URL          : http://flatpak.org/
License      : LGPLv2+
Description  : flatpak is a system for building, distributing and running
             : sandboxed desktop applications on Linux. See
             : https://wiki.gnome.org/Projects/SandboxedApps for more
             : information.
Hope this helps.

**Comment by cw9000** [comment] 2018-04-04 22:27
I'm having the same issues as jmarinho73.  The new version allows me to add them, but not play them ,with the import message appearing as well.

**Comment by TingPing** [comment] 2018-04-05 08:01
Just as an update running with `strace` I don't see any obvious failures, no libraries are missing, and afaict it never actually tries to open the music file.

**Comment by Lonsfor** [comment] 2018-04-06 00:12
The Snap version does work, so i guess its not a problem with Spotify specifically.

**Comment by TingPing** [comment] 2018-04-06 02:57
It isn't the most simple to debug proprietary apps. It is possible the `ffmpeg` version is relevant.

**Comment by angystardust** [comment] 2018-04-08 17:01
sadly enough, same issue here. switching back to the old-but-gold rpm package provided by *negativo17* which doesn't have this issue.

**Closed** 2018-04-10 02:42 UTC

**Comment by jmarinho73** [comment] 2018-04-10 14:19
Problem solved! It works for me. Many thanks!

**Comment by TonyAble** [comment] 2019-12-15 11:28
Having the same problem again.I am using Fedora 31 wayland.
