### ISSUE TITLE
[Fedora] Broken album art, downloads, casting

### ISSUE THREAD

**Issue by agurenko** [flathub/com.spotify.Client#119] opened 2020-01-29 14:46 UTC
Since last week Spotify cannot fetch any album art or download songs offline. Playback seems unaffected. Also control for playback on another devices does not work as the list stays empty. I'm using Fedora 31 with Spotify installed as a system flatpak from flathub.

![Screenshot_20200129_154140](https://user-images.githubusercontent.com/6168150/73366416-36d6a200-42ae-11ea-9efd-c934b2334d3c.png)

**Comment by Erick555** [comment] 2020-01-29 16:34
Duplicate of https://github.com/flathub/com.spotify.Client/issues/116 . See https://github.com/p11-glue/p11-kit/issues/275 for explanation.

**Closed** 2020-01-30 03:27 UTC
