### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by escrevebastante** [flathub/com.spotify.Client#68] opened 2018-12-11 14:10 UTC
I installed spotify with:

flatpak install flathub com.spotify.Client

And the icons for Spotify are missing on the desktop (specifically on the left corner of the window bar and PulseAudio volume)

i also tried installing with the --user option as described here:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1300

but that didn't make any change also. I am using "gnome" as my icon theme and running xfce4 as my desktop environment.

**Comment by Erick555** [comment] 2018-12-12 12:35
I can confirm same behavior under KDE.

Actually using` --user` option was ruled out as a fix in thread you linked but someone recommended using ["copy-icon": true](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1300#issuecomment-394278316) in the manifest.

**Comment by TingPing** [comment] 2018-12-12 14:51
Since Spotify is proprietary any icon references inside the application cannot be fixed, which I imagine is where this is set.

**Comment by Erick555** [comment] 2018-12-12 15:23
Will copy-icon and or rename-icon help?

**Comment by TingPing** [comment] 2018-12-12 19:10
@Erick555 	No. The copies are internal to the flatpak so external services like tray icons, mpris clients, and the pulseaudio daemon won't see them.

**Comment by Erick555** [comment] 2018-12-13 12:49
The icons in PulseAudio volume can be fixed by copying them from `/var/lib/flatpak/app/com.spotify.Client/current/active/export/share/icons` to `~/local/share/icons` and renaming each one of them from `com.spotify.Client.png` to `spotify.png`.

I tried various ways of fixing the window bar icon and it even worked like 1/10 of time but it was not reproducible so I gave up.

**Comment by escrevebastante** [comment] 2018-12-13 21:54
> The icons in PulseAudio volume can be fixed by copying them from `/var/lib/flatpak/app/com.spotify.Client/current/active/export/share/icons` to `~/local/share/icons` and renaming each one of them from `com.spotify.Client.png` to `spotify.png`.
> 
> I tried various ways of fixing the window bar icon and it even worked like 1/10 of time but it was not reproducible so I gave up.

hmm indeed that fixed the icons on pulseaudio. Thanks!
... however, the problem with the icon on the window still remains:

https://i.imgur.com/VQbqiXB.png

**Comment by Erick555** [comment] 2018-12-14 10:36
That one works out of the box in KDE.

**Comment by escrevebastante** [comment] 2018-12-14 14:43
Interesting...the issue is similar with the one described here (yes i know is a completely different application but the same applies):

https://github.com/adobe/brackets/issues/7141

The suggested ugly work-around to that is to use xseticon application (http://www.leonerd.org.uk/code/xseticon/) to force the icon to be loaded on the window in question:

./xseticon -name Spotify ~/.local/share/icons/gnome/24x24/apps/com.spotify.Client.png

And that worked for me... i can see the icon when i press alt+tab and also on the minimize bar... but of course this method is a ugly hack which is far from being ideal... 

any suggestions?

**Comment by azazello4** [comment] 2019-07-12 09:10
Similar (same?) issue here on Fedora 30 - KDE. The icon is replaced by some X.org icon.
[https://i.imgur.com/v2YyCXc.png](url)

**Comment by Poorchop** [comment] 2019-12-15 00:09
I'm on opensuse tumbleweed with xfce. I also installed via command line and even after multiple restarts, Spotify never appeared in my programs list. I didn't even get a generic icon on my desktop or anywhere else. After launching Spotify from the command line, the icon is missing from the task bar itself. There's also a generic placeholder icon in the title bar in the application.

**Comment by thobianchi** [comment] 2020-01-05 22:30
I tried many solution but it was very easy.
Find out where the .desktop is located, mine is at `/var/lib/flatpak/app/com.spotify.Client/current/active/export/share/applications/com.spotify.Client.desktop` you can right click the icon and get it from "Points to".

add **--class=Spotify** to exec command, like this:
```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client --class=Spotify @@u %U @@
```

**class** should match the **StartupWMClass**  value, mine:
```
StartupWMClass=Spotify
```

**Comment by TingPing** [comment] 2020-01-05 22:37
@thobianchi This is already the case by default, `xprop` outputs:

`WM_CLASS(STRING) = "spotify", "Spotify"`

**Comment by TiZ-EX1** [comment] 2020-02-26 19:32
The weird thing that seems to contributing to causing this is that for a very short time when it starts, its window doesn't have any class or class instance name. Sometimes it fixes this before apps like devilspie2 or dockbarx can catch it, but it usually doesn't.

**Comment by TiZ-EX1** [comment] 2020-02-26 20:16
It looks like this is a [known issue for some time](https://community.spotify.com/t5/Desktop-Linux/WM-CLASS-window-property-on-Linux/td-p/1247042) with nothing done about it. Someone [made a little LD_PRELOAD hack](https://github.com/dasJ/spotifywm) to fix it. How would we use that here?

**Comment by TingPing** [comment] 2020-02-26 21:37
Just build it in the manifest and in `spotify-bin` set `LD_PRELOAD`. Testing would be appreciated since I don't really have a desktop where the problem is noticable.

**Comment by HugLifeTiZ** [comment] 2020-10-11 00:28
I'm *finally* getting around to trying to do this, but when I try to install the local build, I get this error:

```
Error: Failed to install com.spotify.Client: While downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.42.622.gbd112320-37_amd64.deb: Connection terminated unexpectedly
```

Looks like Firefox fails to download it too, but I did download it with wget. Can I put it somewhere that the builder will find it and use it instead of trying to download it?

**Closed** 2020-10-30 21:35 UTC

**Comment by eldar** [comment] 2023-02-13 08:19
I installed Spotify on OpenSUSE TumbleWeed KDE and it's not showing the icon.

**Comment by KierPrev** [comment] 2023-03-04 22:26
Same problem on Kubuntu 22.04

**Comment by TingPing** [comment] 2023-03-05 20:33
@eldar @KierPrev It sounds like you should discuss it with KDE folks.

The icon is in `/var/lib/flatpak/exports/share/icons/hicolor/scalable/apps/com.spotify.Client.svg` which should be in `XDG_DATA_DIRS`. If that env var is wrong or KDE is having issues it is outside of this package.
