### ISSUE TITLE
No Media controls in Taskbar Preview in Spotify for kde

### ISSUE THREAD

**Issue by pakosaan** [flathub/com.spotify.Client#208] opened 2022-07-23 06:41 UTC
It works Perfectly with the Aur Packages but not with the flatpak version.

**Comment by Erick555** [comment] 2022-07-23 16:12
Do you mean something else than _Media Player_ applet? That one works for me.

**Comment by TingPing** [comment] 2022-07-25 16:48
Works in GNOME also. The package has rights to `org.mpris.MediaPlayer2.spotify` I wouldn't expect any difference between the host package.

**Comment by TingPing** [comment] 2022-07-25 16:51
KDE tries to associate the window with the mpris instance and fails.

Duplicate of #58

**Closed by TingPing** 2022-07-25 16:51 UTC
